baseURL = 'https://jyvasmetro.fi'
languageCode = 'fi-fi'
title = 'Jyväsmetro 2026'

defaultContentLanguage = 'fi'
[languages]
  [languages.fi]
    languageName = 'suomeksi'
    weight = 1
  [languages.en]
    languageName = 'in English'
    weight = 2

staticDir = ["static"]

disableKinds = ["taxonomy"]

[params]
  name = "Jyväsmetro"
  year = "2026"
  sponsors-year = "2025"
  date = "23.4.2026"
  organizer = "Linkki Jyväskylä ry"
  homepage = "https://linkkijkl.fi"
  countdown = "April 23, 2026 16:00:00"
