baseURL = 'https://jyvasmetro.fi'
languageCode = 'fi-fi'
title = 'Jyv채smetro 2025'

defaultContentLanguage = 'fi'
[languages]
  [languages.fi]
    languageName = 'suomeksi'
    weight = 1
  [languages.en]
    languageName = 'in English'
    weight = 2

staticDir = ["static"]

disableKinds = ["taxonomy"]

[params]
  name = "Jyv채smetro"
  year = "2025"
  date = "24.4.2025"
  organizer = "Linkki Jyv채skyl채 ry"
  countdown = "April 24, 2025 16:00:00"
