name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build translations
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g static-i18n
      - run: static-i18n -l fi -i fi -i en www -o .

      - name: Deploy
        uses: up9cloud/action-rsync@master
        env:
          SOURCE: ./
          ARGS_MORE: --checksum
          VERBOSE: true
          
          HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
